spring:
  application:
    name: msp-dc2-dockops
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable
    database: postgres
    username: postgres
    password: 
#    driverClassName: com.mysql.cj.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baselineOnMigrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#       ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
server:
  port: 8090
logging:
  level:
    root: INFO
    org.springframework: WARN
    path: ${LOG_PATH}
  file:
    main:
      rollingPolicy:
        maxIndex: 10
      triggeringPolicy:
          maxFileSize: 75MB
